import { useMemo, useState } from 'react'
import { FiFileText, FiTrash2, FiUpload } from 'react-icons/fi'
import { PDFUpload } from '../components/pdf/PDFUpload'
import { Card } from '../components/ui/Card'
import { EmptyState } from '../components/ui/EmptyState'
import { Loader } from '../components/ui/Loader'
import { MarkdownContent } from '../components/chat/MarkdownContent'
import { usePageTitle } from '../hooks/usePageTitle'
import { useActivity } from '../hooks/useActivity'
import { useToast } from '../hooks/useToast'
import { summarizePdf } from '../services/pdfService'

export default function PDFSummarizer() {
  usePageTitle('PDF Summarizer')
  const [file, setFile] = useState(null)
  const [summary, setSummary] = useState('')
  const [progress, setProgress] = useState(0)
  const [loading, setLoading] = useState(false)
  const { addToast } = useToast()
  const { recordActivity } = useActivity()

  const summaryState = useMemo(() => {
    if (loading) return 'Uploading and summarizing your file...'
    if (summary) return 'Summary ready'
    return 'Upload a document to get started'
  }, [loading, summary])

  const handleFileChange = (event) => {
    const nextFile = event.target.files?.[0]
    if (!nextFile) return

    if (nextFile.type !== 'application/pdf') {
      addToast({ variant: 'error', title: 'Invalid file', description: 'Please select a PDF document.' })
      return
    }

    setFile(nextFile)
    setSummary('')
    setProgress(0)
  }

  const handleSubmit = async () => {
    if (!file || loading) return

    setLoading(true)
    setProgress(12)

    try {
      const response = await summarizePdf(file, (event) => {
        if (!event.total) return
        const percent = Math.min(95, Math.round((event.loaded / event.total) * 100))
        setProgress(percent)
      })

      setSummary(response.summary)
      setProgress(100)
      recordActivity({
        type: 'pdf',
        title: `Summarized ${response.filename}`,
        description: response.summary,
        meta: { filename: response.filename },
      })
      addToast({ variant: 'success', title: 'Summary complete', description: `${response.filename} has been summarized.` })
    } catch (requestError) {
      const message = requestError?.response?.data?.detail || 'Unable to summarize the PDF right now.'
      addToast({ variant: 'error', title: 'Summary failed', description: message })
    } finally {
      setLoading(false)
      window.setTimeout(() => setProgress(0), 1000)
    }
  }

  const resetState = () => {
    setFile(null)
    setSummary('')
    setProgress(0)
    addToast({ variant: 'info', title: 'Upload cleared', description: 'Select a new PDF to summarize.' })
  }

  return (
    <div className="grid gap-6 xl:grid-cols-[0.95fr_1.05fr]">
      <div className="space-y-6">
        <PDFUpload file={file} progress={progress} onFileChange={handleFileChange} onSubmit={handleSubmit} loading={loading} />

        <Card>
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-sm text-slate-400">Summary status</p>
              <h2 className="mt-1 text-xl font-semibold text-white">{summaryState}</h2>
            </div>
            <button
              type="button"
              onClick={resetState}
              className="inline-flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200 hover:bg-white/10"
            >
              <FiTrash2 />
              Reset
            </button>
          </div>

          <div className="mt-5 rounded-2xl border border-white/10 bg-white/5 px-4 py-4 text-sm leading-7 text-slate-300">
            Summaries are generated by the backend endpoint <span className="font-mono text-cyan-200">POST /api/pdf/summarize</span> using multipart form data.
          </div>
        </Card>
      </div>

      <Card className="min-h-[32rem]">
        <div className="flex items-center justify-between gap-4">
          <div>
            <p className="text-sm text-slate-400">Markdown output</p>
            <h2 className="mt-1 text-xl font-semibold text-white">Summary preview</h2>
          </div>
          <div className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-400/10 text-xl text-cyan-300">
            <FiFileText />
          </div>
        </div>

        <div className="mt-6">
          {loading ? (
            <Loader fullScreen label="Extracting text and generating summary" />
          ) : summary ? (
            <div className="prose prose-invert max-w-none">
              <MarkdownContent content={summary} />
            </div>
          ) : (
            <EmptyState
              icon={<FiUpload />}
              title="No summary yet"
              description="Upload a PDF to generate a concise markdown summary with headings and bullet points."
            />
          )}
        </div>
      </Card>
    </div>
  )
}